version: 0.2

phases:

 install:
  commands:
    - echo "Full environment:"
    - printenv

  pre_build:
    commands:
      - echo "Logging into Amazon ECR"
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

  build:
    commands:
      - echo "values ${BUILD_TRIGGER} / ${CODEBUILD_RESOLVED_SOURCE_VERSION} / ${CODEBUILD_SOURCE_VERSION}"
      - echo Build started on `date`
      - echo Building the docker image
      - docker pull $ECR_REPOSITORY/poc-cf-packer-asg || true
      - docker build -t $ECR_REPOSITORY/poc-cf-packer-asg --cache-from $ECR_REPOSITORY/poc-cf-packer-asg .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the docker image
      - docker push $ECR_REPOSITORY/poc-cf-packer-asg