#
#  cf-packer-asg CloudFormation template
#
#  resources:
#     * CodeBuild Project
#     * ECR
#     * ELB (Classic)
#     * AutoScaleGroup
#
#

Description: PoC of using CodeBuild with packer to create AMIs that are deployed to an ASG

Outputs:
  EcrArn:
    Value: !GetAtt EcrRepository.Arn

Resources:
  EcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: poc-cf-packer-asg
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      ServiceRole: !Ref CodeBuildRole
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/docker:17.09.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: ECR_REPOSITORY
            Value: !Ref EcrRepository
          - Name: AWS_ACCOUNT_ID
            Value: !Ref "AWS::AccountId"
      Source:
        Type: GITHUB
        Location: https://github.com/coopernurse/cf-packer-asg.git
      Triggers:
        Webhook: true
      TimeoutInMinutes: 15
  CodeBuildPackerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref CodeBuildRole
      InstanceProfileName: CodeBuildPackerInstanceProfile
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: ["codebuild.amazonaws.com", "ec2.amazonaws.com"]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 'logs:*'
                - 'ec2:CreateNetworkInterface'
                - 'ec2:DescribeNetworkInterfaces'
                - 'ec2:DeleteNetworkInterface'
                - 'ec2:DescribeSubnets'
                - 'ec2:DescribeSecurityGroups'
                - 'ec2:DescribeDhcpOptions'
                - 'ec2:DescribeVpcs'
                - 'ec2:CreateNetworkInterfacePermission'
                - 'ec2:AttachVolume'
                - 'ec2:AuthorizeSecurityGroupIngress'
                - 'ec2:RevokeSecurityGroupIngress'
                - 'ec2:CopyImage'
                - 'ec2:CreateImage'
                - 'ec2:CreateKeypair'
                - 'ec2:CreateSecurityGroup'
                - 'ec2:CreateSnapshot'
                - 'ec2:CreateTags'
                - 'ec2:CreateVolume'
                - 'ec2:DeleteKeypair'
                - 'ec2:DeleteSecurityGroup'
                - 'ec2:DeleteSnapshot'
                - 'ec2:DeleteVolume'
                - 'ec2:DeregisterImage'
                - 'ec2:DescribeImageAttribute'
                - 'ec2:DescribeImages'
                - 'ec2:DescribeInstances'
                - 'ec2:DescribeRegions'
                - 'ec2:DescribeSnapshots'
                - 'ec2:DescribeTags'
                - 'ec2:DescribeVolumes'
                - 'ec2:DetachVolume'
                - 'ec2:GetPasswordData'
                - 'ec2:ModifyImageAttribute'
                - 'ec2:ModifyInstanceAttribute'
                - 'ec2:ModifySnapshotAttribute'
                - 'ec2:RegisterImage'
                - 'ec2:RunInstances'
                - 'ec2:StartInstances'
                - 'ec2:StopInstances'
                - 'ec2:RebootInstances'
                - 'ec2:TerminateInstances'
                - 'ecr:BatchCheckLayerAvailability'
                - 'ecr:CompleteLayerUpload'
                - 'ecr:GetAuthorizationToken'
                - 'ecr:InitiateLayerUpload'
                - 'ecr:PutImage'
                - 'ecr:UploadLayerPart'
                - 'ecr:GetDownloadUrlForLayer'
                - 'ecr:GetRepositoryPolicy'
                - 'ecr:DescribeRepositories'
                - 'ecr:ListImages'
                - 'ecr:DescribeImages'
                - 'ecr:BatchGetImage'
                # required to allow packer to use iam_instance_profile
                - 'iam:PassRole'
                Effect: Allow
                Resource: '*'
